### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by joaomcteixeira** [osita-sunday-nnyigide/Pras_Server#1]
Hi.

I am trying to use PRAS C++ version locally. I am getting `Segmentation fault`, and I can't identify why. May be you can help me out. I am doing the following:

1. Download the 3SHI (random PDB just for testing)
2. installed PRAS after cloning and doing `g++ -std=c++17 -ffast-math -O3 src/*.cpp -o PRAS`
3. I have installed FASPR, also
4. `FASPR -i 3SHI.pdb -o faspr/3SHI.pdb`
5. `PRAS -i 3SHI.pdb -f faspr/3SHI.pdb -r yes -m yes -l no -h no -p no -s no`.

```
************************************************************
            PRAS 1.0.10
Protein Repair and Analysis Server

Copyright (c) 2022 Osita Sunday Nnyigide
Complex Fluid Laboratory
School of Chemical and Biomolecular Engineering
Pusan National University
Email:osita@protein-science.com
************************************************************

**Now checking and fixing missing heavy atoms...
Segmentation fault (core dumped)
```

Am I missing something? Have I not installed the Python version of Pras.

Many thanks,

**Comment by osita-sunday-nnyigide** [comment]
Thank you for using PRAS Server.

I would like you to follow these steps:

Before installing faspr, please make the following changes in the source code (there is a PDF document I included in the python distribution of PRAS server that explains this)

1. In line 72 of FASPR.cpp change string pdbin=(string)"example/1mol.pdb" to string pdbin=(string)“.“
2. In line 73 of FASPR.cpp change string pdbout=(string)"example/1mol_FASPR.pdb" to string pdbout=(string)“.“

Then install the program as usual (i.e., g++ -ffast-math -O3 -o FASPR src/*.cpp)
Download your protein (3shi.pdb) from the protein data bank
Process your protein using FASPR as ./FASPR -i 3shi.pdb -o xxx.pdb
If this directroy is not where you installed PRAS server, you should copy xxx.pdb to the directory where you installed PRAS
Then process your 3shi with PRAS using ./PRAS -i 3shi.pdb -f xxx.pdb -r yes -m yes -l no -h no -p no -s no

I did the above and it ran successfully. You will not get the warning in log.txt "No faspr output PDB is supplied, default chi will be used". This indicates that PRAS read xxx.pdb from faspr and used the chi of any residue that requires fixing to repair your protein. Interestingly,  3shi.pdb has no missing atoms as I found the log.txt generated by PRAS empty!

IMPORTANT: You can name your FASPR out put pdb any name except out.pdb as PRAS is meant to remove any out.pdb when repairing your protein. The repaired protein will be named out.pdb.

If you encounter any further problem do not hesitate to contact me.

Thank you.

**Comment by joaomcteixeira** [comment]
Thanks so much for the quick reply. I will test it and let you know.  Best!

**Comment by joaomcteixeira** [comment]
Hi @osita-sunday-nnyigide 

I tried your suggestion.

1. edited the `FASPR.cpp` code as you said and recompiled:

```c++
  string pdbin=(string)".";
  string pdbout=(string)".";
  string seqfile=(string)"void";
```

And keep getting a segmentation fault. I tried with `FASPR` and `PRAS` on the same folder (`CWD`) together with the PDBs.

I could run the `linux_example.py` after installing `pip install Pras-Server==1.0.10`. But I was expecting to be able to run it without installing the Python version and using only C++. I have other questions related to the functioning of the software that I will ask you on different issues—many thanks.

**Comment by osita-sunday-nnyigide** [comment]
Okay, let's try this:

Run PRAS with a dummy faspr input. That is, process your PDB with this syntax/command:

./PRAS -i 3shi.pdb -f none -r yes -m yes -l no -h no -p no -s no

Please confirm that your protein (3shi) is a .pdb and not .ent and also ensure it is in the right case (the one I'm using along with you is in lowercase, 3shi.pdb and not  3SHI.pdb

I just removed PRAS and reinstalled it now from the github repo and it worked fine again for 3shi.pdb without any problem

Let me know the outcome as soon as you try it. We need to confirm that PRAS works on your machine.

**Comment by joaomcteixeira** [comment]
Hi,

I could make it work by recompiling without the `fast-math` flag, simply:

```bash
g++ -std=c++17 src/*.cpp -o PRAS
```

In this case, the command above you gave will **only** complete the missing heavy atoms. Is that it?

Many thanks

**Comment by osita-sunday-nnyigide** [comment]
Oh I see.
Yes, the command will fix missing heavy atoms (if there is any).
Repair notes are written in log.txt file generated by PRAS.
You will find all missing atoms that were fixed in  log.txt
If  log.txt  is empty, it means there is no missing atom.

INSTALL.md file  included in the distribution has the fllowing line:

USAGE

./PRAS -i in.pdb -f faspr.pdb -r yes -m yes -l no -h no -p no -s no

-i (input)     enter input PDB to repair and/or analyze
-f (faspr)     enter input PDB as obtained from FASPR or a dummy value to use default chi
-r (rotamer)   enter yes to use high occupancy atoms or a dummy value for low occupancy
-m (mutation)  enter yes to use high occupancy atoms or a dummy value for low occupancy
-l (ligand)    enter yes to keep non-water ligands or a dummy value to ignore them
-h (hydrogen)  enter yes to add hydrogen atoms or a dummy value to do otherwise
-p (protonate) enter yes to protonate 20% of histidines or a dummy value to do otherwise
-s (structure) enter yes to assign secondary structure elements or a dummy value to do otherwise

Thank you!

**Comment by joaomcteixeira** [comment]
Many thanks.
With the `--fast-math` flag I understand the C++ version is 2 or 3 times faster than the python version. That's enough. It's not relevant why it broke on my computer with that flag.
Many thanks. I think this can be close.
Best and thanks for your software!

**Comment by osita-sunday-nnyigide** [comment]
Thank you!
