### ISSUE TITLE
Specifying encoding in CheckPDBatoms.py

### ISSUE THREAD

**Issue by isty2e** [osita-sunday-nnyigide/Pras_Server#3]
In line 281:
```python
with open('log.txt', 'a') as log:
```
This can be changed as the following for the sake of safety:
```python
with open('log.txt', 'a', encoding="utf8") as log:
```

This should not raise any exception normally, but I have encountered an issue when trying to use it after processing with pdbfixer. When adding missing atoms with pdbfixer (which I have used to add missing main chain atoms), the OpenMM minimization step inside it somehow magically changes the encoding to ASCII ([related issue](https://github.com/deepmind/alphafold/issues/483)). Then the en dash in L288 causes the following error:
```
  File ".../conda/envs/py310/lib/python3.10/site-packages/Pras_Server/CheckPDBatoms.py", line 283, in checkpdbAtoms
    log.write('When using files generated by this program in a publication,'
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 349: ordinal not in range(128)
```

 This is a problem in OpenMM, but without knowing how to fix it for now, I think it is a safe solution for now.

**Comment by osita-sunday-nnyigide** [comment]
Hello, I have effected the correction in line 281 of CheckPDBatoms.py.

Thank you very much!
