### ISSUE TITLE
Covalent Ligands not supported

### ISSUE THREAD

**Issue by brgstfzj** [osita-sunday-nnyigide/Pras_Server#4]
when using the server with a structure that contains a covalent ligand, the bond that is described in the 'LINK' line is being deleted. Also all bonds described by the 'CONECT' lines are missing.

you can check this by using the server with e.g. 7K6D or 7TLL

**Comment by osita-sunday-nnyigide** [comment]
Hi, if you have ligands in your PDB structure file and you want to keep them, you should select the option that says "Keep ligands". In the case of 7K6D, I observed that CYS145 is covalently bonded to SV6, which is a ligand. Without selecting the option to keep the ligand, it will be ignored. Note that PRAS server neither repairs ligands nor adds hydrogen atoms to them. The server will only keep the ligand structure if you select the option to do so. I hope this is what you were trying to achieve with 7K6D  and 7TLL

Take care.

**Comment by brgstfzj** [comment]
Thanks for the quick answer.

yes, I did use the "keep ligands" option. What I wanted was to add the atoms that are missing for standard amino acid residues. So just repairing the file while keeping the covalent ligand.

The issue is that after using the server with a structure that contains a covalent ligand, the output pdb file is not complete. With covalent ligands, there are additional lines in the pdb file that describe the connectivity between the HETATMs (CONECT lines). and LINK lines that describe the bonds between the covalent ligand and some standard amino acid residue.

Without these essential lines, there are just random additional atoms floating around that are not connected to anything.

I would have expected the server to add the LINK and CONECT lines into the file and adjust the respective serial numbers in the CONECT lines.

so, for the case of 7K6D, the following lines are missing:
`LINK         SG  CYS A 145                 CAI SV6 A 402     1555   1555  1.78`   (which can just be transfered, nothing changes.)
and the serial numbers in the CONECT lines have to shifted according to how many atoms have been inserted before the respective atom.

**Comment by osita-sunday-nnyigide** [comment]
Hi, I understand what you mean. If they appear as  "random additional atoms
floating around that are not connected to anything" it means the
visualization software you are using does not use atomic distances to
assign covalent bonds.
Normally, I use PyMOL which has no problem displaying the PRAS-generated
PDB structure. You can add the CONECT records by saving a PRAS-repaired
copy using PyMOL.

I will update the server soon to include these records.

Thank you.

**Comment by brgstfzj** [comment]
Thanks!

I am actually not using any visualization software but just work with plain pdb file text data. :sweat_smile:

**Comment by osita-sunday-nnyigide** [comment]
Okay, as I mentioned, you can use PyMOL to add the CONECt if you want.

Take care
